"""
===============================================================================
Unit Tests: utils/jira_client.py
===============================================================================
Tests ticket ID extraction and result-comment formatting — pure logic with
no network calls.

Author: PMAC
===============================================================================
"""

import pytest

from utils.jira_client import JiraClient, JiraTestResult, extract_ticket_id


# ------------------------------------------------------------------------------
# extract_ticket_id
# ------------------------------------------------------------------------------


class TestExtractTicketId:
    @pytest.mark.parametrize(
        "nodeid,expected",
        [
            ("tests/ABC-123/test_login.py::test_valid_login", "ABC-123"),
            ("tests/test_login.py::test_login[PROJ-9]", "PROJ-9"),
            ("tests/test_x.py::test_login[AB2-42]", "AB2-42"),
            ("ABC-123", "ABC-123"),
        ],
    )
    def test_extracts_ticket_pattern(self, nodeid, expected):
        assert extract_ticket_id(nodeid) == expected

    @pytest.mark.parametrize(
        "nodeid",
        [
            "tests/login/test_login.py::test_valid_login",
            "tests/abc-123/test_lowercase.py::test_x",
            "",
            "A-123",  # project key needs at least two characters
        ],
    )
    def test_returns_none_when_no_ticket(self, nodeid):
        assert extract_ticket_id(nodeid) is None

    def test_underscore_prefix_blocks_word_boundary(self):
        # Ticket IDs embedded directly in snake_case names don't match because
        # "_" is a word character, so no \b exists before the project key.
        assert extract_ticket_id("tests/test_login.py::test_ABC-123_flow") is None

    def test_returns_first_match_when_multiple(self):
        assert extract_ticket_id("tests/ABC-1/test.py::test[XYZ-2]") == "ABC-1"


# ------------------------------------------------------------------------------
# JiraClient.format_result_comment
# ------------------------------------------------------------------------------


class TestFormatResultComment:
    def _result(self, **overrides):
        defaults = {
            "ticket_id": "ABC-123",
            "test_name": "test_valid_login",
            "status": "passed",
            "duration_ms": 150,
        }
        defaults.update(overrides)
        return JiraTestResult(**defaults)

    def test_passed_comment_contents(self):
        result = self._result()
        comment = JiraClient().format_result_comment(result)
        assert "✅" in comment
        assert "*Test:* test_valid_login" in comment
        assert "*Status:* PASSED" in comment
        assert "*Duration:* 150ms" in comment
        assert result.timestamp in comment
        assert "Error Details" not in comment

    def test_failed_comment_includes_error_block(self):
        result = self._result(status="failed", error_message="element not found")
        comment = JiraClient().format_result_comment(result)
        assert "❌" in comment
        assert "*Status:* FAILED" in comment
        assert "{code}" in comment
        assert "element not found" in comment

    def test_failed_error_message_truncated_to_2000_chars(self):
        result = self._result(status="failed", error_message="x" * 5000)
        comment = JiraClient().format_result_comment(result)
        assert "x" * 2000 in comment
        assert "x" * 2001 not in comment

    def test_error_message_ignored_unless_failed(self):
        result = self._result(status="passed", error_message="should not appear")
        comment = JiraClient().format_result_comment(result)
        assert "should not appear" not in comment

    def test_skipped_and_unknown_status_emojis(self):
        client = JiraClient()
        assert "⏭️" in client.format_result_comment(self._result(status="skipped"))
        assert "❓" in client.format_result_comment(self._result(status="mystery"))

    def test_test_file_rendered_in_jira_noformat_braces(self):
        result = self._result(test_file="tests/login/test_login.py")
        comment = JiraClient().format_result_comment(result)
        assert "{{tests/login/test_login.py}}" in comment

    def test_footer_present(self):
        comment = JiraClient().format_result_comment(self._result())
        assert "automatically generated by playwright-ai-framework" in comment
